[package]
name = "dgmark"
version = "0.1.0"
edition = "2018"

[dependencies]
nom = "7.0.0"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }

[[bench]]
name = "document"
harness = false
